config/routes.rb
require 'duckrails/router'

Rails.application.routes.draw do
  root 'duckrails/home#index'

  namespace 'duckrails' do
    resources :mocks, except: [:show] do
      member do
        put :activate
        put :deactivate
      end

      collection do
        put :update_order
      end
    end
  end

  Duckrails::Router.load_mock_routes!
end

app/models/duckrails/application_state.rb
require 'duckrails/synchronizer'

module Duckrails
  # The application state
  class ApplicationState < ActiveRecord::Base
    self.table_name = 'application_state'

    default_scope { order(id: :desc) }

    validates :singleton_guard, inclusion: { in: [0] }
    validates :mock_synchronization_token, presence: true

    def update_token(type)
      case type
      when :mock
        self.mock_synchronization_token = Synchronizer.generate_token
        save
      end
    end

    class << self
      # @return [ApplicationState] the one and only application state
      def instance
        ApplicationState.first || ApplicationState.create(singleton_guard: 0,
                                                          mock_synchronization_token: Synchronizer.generate_token)
      end
    end
  end
end

app/models/duckrails/header.rb
class Duckrails::Header < ActiveRecord::Base
  belongs_to :mock, inverse_of: :headers

  validates :name, presence: true
  validates :value, presence: true
  validates :mock, presence: true
end

app/models/duckrails/mock.rb
class Duckrails::Mock < ActiveRecord::Base
  SCRIPT_TYPE_EMBEDDED_RUBY = 'embedded_ruby'
  SCRIPT_TYPE_JS = 'js'
  SCRIPT_TYPE_STATIC = 'static'

  has_many :headers, dependent: :destroy, inverse_of: :mock
  accepts_nested_attributes_for :headers, allow_destroy: true, reject_if: :all_blank

  validates :status, presence: true
  validates :request_method, presence: true
  validates :content_type, presence: true
  validates :route_path, presence: true, route: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :body_type, inclusion: { in: [SCRIPT_TYPE_STATIC,
                                          SCRIPT_TYPE_EMBEDDED_RUBY,
                                          SCRIPT_TYPE_JS],
                                     allow_blank: true },
                        presence: { unless: 'body_content.blank?' }
  validates :body_content, presence: { unless: 'body_type.blank?' }
  validates :script_type, inclusion: { in: [SCRIPT_TYPE_STATIC,
                                            SCRIPT_TYPE_EMBEDDED_RUBY,
                                            SCRIPT_TYPE_JS],
                                     allow_blank: true },
                          presence: { unless: 'script.blank?' }
  validates :script, presence: { unless: 'script_type.blank?' }
  validates :active, presence: { if: 'active.nil?' }

  before_save :set_order
  after_save :register
  after_destroy :unregister

  default_scope { order(mock_order: :asc) }

  def dynamic?
    body_type != SCRIPT_TYPE_STATIC
  end

  def activate!
    self.update_attributes!(active: true)
  end

  def deactivate!
    self.update_attributes!(active: false)
  end

  #########
  protected
  #########

  def set_order
    self.mock_order ||= (Duckrails::Mock.maximum(:mock_order) || 0) + 1
  end

  def register
    Duckrails::Router.register_mock self
  end

  def unregister
    Duckrails::Router.unregister_mock self
  end
end

app/controllers/duckrails/home_controller.rb
module Duckrails
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/duckrails/mocks_controller.rb
require 'duckrails/router'
require 'libxml'

module Duckrails
  class MocksController < ApplicationController
    before_action :load_mock, only: [:edit, :update, :destroy, :deactivate, :activate]
    after_action :reload_routes, only: [:update, :create, :destroy, :deactivate, :activate, :update_order]

    skip_before_action :verify_authenticity_token, :only => [:serve_mock]

    def index
      if params[:sort]
        @mocks = Duckrails::Mock.all
        render :sort_index
      else
        @mocks = Duckrails::Mock.page(params[:page]).per(params[:per])
      end
    end

    def edit
    end

    def new
      @mock = Duckrails::Mock.new
    end

    def update
      @mock.assign_attributes mock_params

      if @mock.save
        redirect_to duckrails_mocks_path, flash: { info: 'The mock was successfully updated.' }
      else
        @skip_reloading = true
        render :edit
      end
    end

    def update_order
      Duckrails::Mock.transaction do
        params[:order].values.each do |mock_order|
          mock = Duckrails::Mock.find(mock_order[:id])
          mock.update_attribute(:mock_order, mock_order[:order])
        end
      end

      render nothing: true
    end

    def create
      @mock = Duckrails::Mock.new mock_params

      if @mock.save
        redirect_to duckrails_mocks_path, flash: { info: 'The mock was created successfully.' }
      else
        @skip_reloading = true
        render :new
      end
    end

    def destroy
      @mock.delete
      Duckrails::Router.unregister_mock @mock
      redirect_to duckrails_mocks_path, flash: { info: "Mock '#{@mock.name}' was deleted successfully." }
    end

    def activate
      @mock.activate!
      redirect_to duckrails_mocks_path
    end

    def deactivate
      @mock.deactivate!
      redirect_to duckrails_mocks_path
    end

    # This is the one and only action mapped to each mock route
    def serve_mock
      mock = Duckrails::Mock.find params[:duckrails_mock_id]
      overrides = (evaluate_content(mock.script_type, mock.script, true) || {}).with_indifferent_access

      mock.headers.each do |header|
        add_response_header header
      end

      if overrides[:headers]
        overrides[:headers].each do |header|
          add_response_header header
        end
      end

      status = overrides[:status_code] || mock.status
      content_type = overrides[:content_type] || mock.content_type
      body = overrides[:body] || evaluate_content(mock.body_type, mock.body_content)

      render body: body, content_type: content_type, status: status
    end

    def default_url_options
      {
        page: params[:page],
        per: params[:per]
      }
    end

    #########
    protected
    #########

    def add_response_header(header)
      response.headers[header[:name]] = header[:value]
    end

    def evaluate_content(script_type, script, force_json = false)
      return nil unless script_type.present?

      result = case script_type
        when Duckrails::Mock::SCRIPT_TYPE_STATIC
          script
        when Duckrails::Mock::SCRIPT_TYPE_EMBEDDED_RUBY
          context_variables = {
            response: response,
            request: request,
            headers: Hash[request.headers.select{ |header| header[1].is_a? String }],
            parameters: params
          }

          Erubis::Eruby.new(script).evaluate(context_variables)
        when Duckrails::Mock::SCRIPT_TYPE_JS
          headers = request.headers.select do |header|
            header[1].is_a? String
          end

          context = ExecJS.compile("parameters = #{params.to_json}; headers = #{Hash[headers].to_json}")
          context.exec script
      end unless script.blank?

      force_json ? JSON.parse(result.blank? ? '{}' : result) : result
    rescue StandardError => error
      response.headers['Duckrails-Error'] = error.to_s
      logger.error error.message
      logger.error error.backtrace.join "\n"
      nil
    end

    def reload_routes
      Duckrails::Router.reload_routes! unless @skip_reloading
    end

    def mock_params
      params.require(:duckrails_mock).permit(:name,
                                             :description,
                                             :status,
                                             :body_type,
                                             :body_content,
                                             :script_type,
                                             :script,
                                             :request_method,
                                             :content_type,
                                             :route_path,
                                             :active,
                                             headers_attributes: [:id,
                                                                  :name,
                                                                  :value,
                                                                  :_destroy])
    end

    def load_mock
      @mock = Duckrails::Mock.find params[:id]
    end
  end
end

app/helpers/duckrails/mocks_helper.rb
module Duckrails
  module MocksHelper
    def available_mime_types
      Mime::EXTENSION_LOOKUP.map{ |a| a[1].to_s }.uniq.sort
    end

    def available_script_types
      [ [t(Duckrails::Mock::SCRIPT_TYPE_EMBEDDED_RUBY), Duckrails::Mock::SCRIPT_TYPE_EMBEDDED_RUBY],
        [t(Duckrails::Mock::SCRIPT_TYPE_JS), Duckrails::Mock::SCRIPT_TYPE_JS],
        [t(Duckrails::Mock::SCRIPT_TYPE_STATIC), Duckrails::Mock::SCRIPT_TYPE_STATIC] ]
    end
  end
end

app/views/duckrails/mocks/_form.html.erb
<%= simple_form_for @mock, html: { class: 'mock-form' } do |form| %>
  <ul class="tabs" data-tab>
    <li class="tab-title active"><a href="#general">General</a></li>
    <li class="tab-title"><a href="#response_body">Response body</a></li>
    <li class="tab-title"><a href="#headers">Headers</a></li>
    <li class="tab-title"><a href="#advanced">Advanced</a></li>
  </ul>

  <div class="tabs-content">
    <div class="content active" id="general">
      <p><%= t :general_tab_header  %></p>

      <div class="row">
        <div class="small-12 medium-10 columns">
          <%= form.input :name, hint: t(:field_name_hint) %>
        </div>

        <div class="small-12 medium-2 columns text-right">
          <label>&nbsp;</label>
          <%= form.input :active, hint: t(:field_active_hint), wrapper_html: { class: 'checkbox-wrapper' } %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">
          <%= form.input :description, input_html: { class: 'short' }, hint: t(:field_description_hint) %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 medium-6 columns">
          <%= form.input :request_method, collection: Duckrails::Router::METHODS, hint: t(:field_request_method_hint) %>
        </div>

        <div class="small-12 medium-6 columns">
          <%= form.input :status, hint: t(:field_status_hint) %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">
          <%= form.input :route_path, hint: t(:field_route_path_hint) %>
        </div>
      </div>
    </div>

    <div class="content" id="response_body">
      <p><%= t :response_body_tab_header %></p>

      <div class="row">
        <div class="small-12 medium-6 columns">
          <%= form.input :body_type, collection: available_script_types, include_blank: true, hint: t(:field_body_type_hint) %>
        </div>

        <div class="small-12 medium-6 columns">
          <%= form.input :content_type, collection: available_mime_types, include_blank: true, hint: t(:field_content_type_hint) %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">
          <%= form.input :body_content, input_html: { class: 'tall' }, hint: t(:field_body_content_hint) %>
        </div>
      </div>
    </div>

    <div class="content" id="headers">
      <div class="right">
        <%= link_to_add_association form,
                                    :headers,
                                    title: t(:add_header_link_title),
                                    data: {
                                      association_insertion_method: 'append',
                                      association_insertion_node: '.mock-headers'
                                      } do %>
          <i class="fa fa-plus"></i>
          <span><%= t(:add_header) %></span>
          <% end %>
      </div>
      <p><%= t :headers_tab_header %></p>

      <div class="row">
        <div class="small-12 columns mock-headers">
          <%= form.simple_fields_for :headers do |header_fields| %>
            <%= render partial: 'header_fields', locals: { f: header_fields } %>
          <% end %>

        </div>
      </div>
    </div>

    <div class="content" id="advanced">
      <p><%= t :advanced_tab_header %></p>

      <div class="row">
        <div class="small-12 medium-6 columns">
          <%= form.input :script_type, collection: available_script_types, include_blank: true, hint: t(:field_script_type_hint) %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">
          <%= form.input :script, input_html: { class: 'tall' }, hint: t(:field_script_hint) %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-4 columns">
      <% if @mock.new_record? %>
        &nbsp;
      <% else %>
        <%= link_to(t(:delete), duckrails_mock_path(@mock), method: :delete, class: 'button alert expand', data: { confirm: t(:mock_deletion_confirmation) }) %>
      <% end %>
    </div>

    <div class="small-12 medium-4 columns">
      <%= link_to t(:cancel), duckrails_mocks_path, class: 'button secondary expand' %>
    </div>

    <div class="small-12 medium-4 columns end">
      <%= form.submit t(:save), class: 'button expand' %>
    </div>
  </div>
<% end %>

app/views/duckrails/mocks/_header_fields.html.erb
<div class="header-fields">
  <div class="row">
    <div class="small-12 columns">
      <div class="row">
        <div class="small-12 medium-3 columns">
          <%= f.input :name, hint: t(:field_header_name_hint) %>
        </div>

        <div class="small-12 medium-7 columns">
          <%= f.input :value, hint: t(:field_header_value_hint) %>
        </div>

        <div class="small-12 medium-2 columns text-center">
          <label>&nbsp;</label>
          <%= link_to_remove_association f, wrapper_class: 'header-fields', class: 'button tiny' do %>
            <i class="fa fa-remove"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/duckrails/mocks/edit.html.erb
<% title t(:edit_mock) %>
<h1><%= t(:edit_mock_header, mock: @mock.name) %></h1>

<p class="page-guide">
  <%= t :edit_mock_page_guide %>
</p>

<%= render partial: 'form' %>

app/views/duckrails/mocks/index.html.erb
<% title t(:mocks) %>

<h1><%= t :mocks %></h1>

<p class="page-guide">
  <%= t :mocks_index_page_guide %>
</p>

<% if @mocks.blank? %>
  <div class="alert-box warning">
    <%= t :no_mocks_warning %>
  </div>
<% else %>
  <table class="mocks">
      <thead>
        <tr>
          <th><%= t :mock_name %></th>
          <th><%= t :mock_method %></th>
          <th><%= t :mock_route %></th>
          <th class="text-center"><%= t :mock_active %></th>
          <th><%= t :mock_actions %></th>
        </tr>
      <thead>

      <tbody>
        <% @mocks.each do |mock| %>
          <tr data-mock-id="<%= mock.id %>">
            <td>
              <%= mock.name %>
            </td>

            <td>
              <%= mock.request_method %>
            </td>

            <td>
              <%= mock.route_path %>
            </td>

            <td class="text-center">
              <span class="<%= mock.active? ? 'active' : 'inactive' %>">
                <i class="fa fa-<%= mock.active? ? 'check-square-o' : 'square-o' %>"></i>
              </span>
            </td>

            <td class="actions">
              <%= link_to edit_duckrails_mock_path(mock),
                          title: 'Edit mock',
                          class: 'button tiny edit' do %>
                <i class="fa fa-edit"></i>
              <% end %>

              <%= link_to duckrails_mock_path(mock), method: :delete,
                                           title: 'Delete mock',
                                           data: {
                                             confirm: t(:mock_deletion_confirmation)
                                           }, class: 'button tiny delete' do %>
                <i class="fa fa-remove"></i>
              <% end %>

              <%= link_to deactivate_duckrails_mock_path(mock), method: :put,
                                           title: 'Deactivate mock',
                                           data: {
                                             confirm: t(:mock_deactivation_confirmation)
                                           }, class: 'button tiny deactivate secondary' do %>
                <i class="fa fa-pause"></i>
              <% end if mock.active? %>

              <%= link_to activate_duckrails_mock_path(mock), method: :put,
                                           title: 'Activate mock',
                                           data: {
                                             confirm: t(:mock_activation_confirmation)
                                           }, class: 'button tiny activate success' do %>
                <i class="fa fa-play"></i>
              <% end unless mock.active? %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>

  <div class="row">
    <div class="small-12 columns">
      <%= paginate @mocks %>
    </div>
  </div>
<% end %>

<div class="page-actions">
  <div class="row">
    <div class="small-12 columns">
      <%= link_to duckrails_mocks_path(sort: true),
                  title: "Change the order of the mocks",
                  class: 'button secondary' do %>
        <i class="fa fa-bars"></i>
        <span><%= t :change_mocks_order %></span>
      <% end if @mocks.size > 1 %>

      <%= link_to new_duckrails_mock_path,
                  title: "Create a new mock",
                  class: 'button' do %>
        <i class="fa fa-plus"></i>
        <span><%= t :create_new_mock %></span>
      <% end %>
    </div>
  </div>
</div>

app/views/duckrails/mocks/new.html.erb
<% title t(:new_mock) %>
<h1><%= t(:create_new_mock) %></h1>

<p class="page-guide">
  <%= t :new_mock_page_guide %>
</p>

<%= render 'form' %>

app/views/duckrails/mocks/sort_index.html.erb
<% title t(:change_mocks_order) %>

<h1><%= t :change_mocks_order %></h1>

<p class="page-guide">
  <%= t :mocks_sort_index_page_guide %>
</p>

<%= content_tag :div,
                class: 'sortable',
                data: {
                  mock_url: update_order_duckrails_mocks_path,
                  mock_method: :put,
                  mock_success_url: duckrails_mocks_path
                } do %>
    <% @mocks.each do |mock| %>
      <%= content_tag :div, data: { mock_id: mock.id, old_pos: mock.mock_order }, class: 'mock' do %>
        <div class="left mock-name">
          <%= mock.name %>
        </div>

        <div class="right mock-path">
          <%= mock.route_path %>
        </div>

        <div class="right mock-request-method">
          <%= mock.request_method %>
        </div>
      <% end %>
    <% end %>
<% end %>

<div class="page-actions">
  <%= link_to t(:cancel), duckrails_mocks_path, class: 'button secondary' %>

  <%= link_to t(:save), '#', class: 'button success update-mocks-order' %>
</div>