config/routes.rb
require 'duckrails/router'

Rails.application.routes.draw do
  root 'duckrails/home#index'

  namespace 'duckrails' do
    resources :mocks, except: [:show] do
      member do
        put :activate
        put :deactivate
      end

      collection do
        put :update_order
      end
    end
  end

  Duckrails::Router.load_mock_routes!
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="small-12 columns">
      <p>
        <a href="https://github.com/iridakos/duckrails" target="_blank"><strong>DuckRails</strong> v<%= Duckrails::Application::VERSION %></a>
      </p>

      <p>
        Visit application's <a href="https://github.com/iridakos/duckrails/wiki" target="_blank">wiki pages</a> for usage guides and examples.
      </p>

      <p>
        Found a bug or you have something to suggest? Open issues at the <a href="https://github.com/iridakos/duckrails/issues" target="_blank">application's GitHub repository</a>.
      </p>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to root_path, class: 'home-link' do %>
          <%= image_tag 'duck-face-white.png', size: '30x30' %>
          <span>DuckRails</span>
          <span class="version success">v. <%= Duckrails::Application::VERSION %></span>
        <% end %>
      </h1>
    </li>

    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#">Menu</a>
        <ul class="dropdown">
          <li><%= link_to 'View all mocks', duckrails_mocks_path %></li>
          <li><%= link_to 'Create new mock', new_duckrails_mock_path %></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>